// Produce ready-to-send calldata for minting transistors and taping out the Life
// circuits, plus a preflight check of everything that can be checked read-only.
// This script sends nothing: it only writes hex you can paste into a wallet.
import fs from "node:fs";
import { pathToFileURL } from "node:url";
import { encode, compile, decode, step } from "./netlist.mjs";
import { buildRule, buildGrid } from "./build_life.mjs";
import { buildRuleRef, POPCOUNT8 } from "./build_life_ref.mjs";
import { batchCall, callData, SEL } from "./rpc.mjs";

const SELECTORS = {
  tapeout: "7bd3ac1d",   // tapeout(bytes,uint32,uint32)
  mint: "1b2ef1ca",      // mint(uint256,uint256)
};

const pad = (v) => BigInt(v).toString(16).padStart(64, "0");
const hex = (b) => Buffer.from(b).toString("hex");

export function tapeoutCalldata(bytes, nIn, nOut) {
  const body = hex(bytes).padEnd(Math.ceil(bytes.length / 32) * 64, "0");
  return "0x" + SELECTORS.tapeout + pad(96) + pad(nIn) + pad(nOut) + pad(bytes.length) + body;
}

export const mintCalldata = (tokenId, amount) => "0x" + SELECTORS.mint + pad(tokenId) + pad(amount);

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const N = Number(process.argv[2] || 8);
  const project = process.argv[3] || null;   // the Circuits contract you will tape out to
  const ruleId = Number(process.argv[4] || 0); // id the rule gets after step 1 (0 = placeholder)

  const out = { note: "generated by make_calldata.mjs — nothing was sent", steps: [] };

  // ---- step 1: the rule circuit
  const rule = buildRule();
  const ruleBytes = encode(rule.els);
  const ruleC = compile(ruleBytes, 10, 1);
  for (let v = 0; v < 1024; v++) {
    const i = [...Array(10).keys()].map((k) => (v >> k) & 1);
    const s = i.slice(0, 8).reduce((a, b) => a + b, 0);
    const want = (s === 3 || (i[8] && s === 2) ? 1 : 0) | i[9];
    if (step(ruleC, new Uint8Array(0), i).outputs[0] !== want) throw new Error("rule self-test failed");
  }
  // round-trip: what we encode must decode back to the same elements
  if (encode(decode(ruleBytes, 10)).join(",") !== ruleBytes.join(",")) throw new Error("rule round-trip failed");

  out.steps.push({
    step: 1, what: "mint transistors for the rule circuit",
    to: "<the project's Transistors (ERC-1155) contract>",
    nand: rule.nNand, latch: rule.nLatch,
    calldata: { NAND: mintCalldata(0, rule.nNand), LATCH: rule.nLatch ? mintCalldata(1, rule.nLatch) : null },
    value: "mintPrice * amount + protocolFee (read mintPrice()/protocolFee() first)",
  });
  out.steps.push({
    step: 2, what: "tape out the rule circuit (10 inputs -> 1 output)",
    to: "<the project's Circuits contract>",
    nIn: 10, nOut: 1, bytes: ruleBytes.length,
    calldata: tapeoutCalldata(ruleBytes, 10, 1),
    value: "TAPEOUT_FEE() — 0.0002 BNB at the time of writing",
    then: "read the TapedOut event for the new circuitId, pass it as argv[4] here",
  });

  // ---- step 3: the grid, referencing the rule
  if (project && ruleId) {
    const grid = buildGrid(N, project, ruleId);
    const gridBytes = encode(grid.els);
    const gc = compile(gridBytes, N * N, N * N, () => ruleC);
    // glider must still work through the real REF target
    let state = new Uint8Array(gc.nState);
    const seed = new Array(N * N).fill(0);
    for (const [r, c] of [[0, 1], [1, 2], [2, 0], [2, 1], [2, 2]]) seed[r * N + c] = 1;
    let res = step(gc, state, seed);
    let board = res.outputs, alive = board.reduce((a, b) => a + b, 0);
    if (alive !== 5) throw new Error(`grid self-test: seeded ${alive} cells, expected 5`);
    out.steps.push({
      step: 3, what: `mint transistors for the ${N}x${N} grid`,
      nand: grid.nNand, latch: grid.nLatch,
      calldata: { NAND: grid.nNand ? mintCalldata(0, grid.nNand) : null, LATCH: mintCalldata(1, grid.nLatch) },
    });
    out.steps.push({
      step: 4, what: `tape out the ${N}x${N} grid (${N * N} inputs -> ${N * N} outputs)`,
      to: project, nIn: N * N, nOut: N * N, bytes: gridBytes.length,
      gatesPerBeat: gc.totalGates,
      estimatedGasPerBeat: Math.round(gc.totalGates * 2468 + 40000),
      calldata: tapeoutCalldata(gridBytes, N * N, N * N),
    });
  } else {
    out.steps.push({ step: 3, what: "rerun as: node make_calldata.mjs <N> <projectCircuitsAddress> <ruleCircuitId>" });
  }

  // ---- preflight that can be done read-only
  if (project) {
    const [nextId, fee] = await batchCall([
      { to: project, data: "0x" + SEL.nextId },
      { to: project, data: "0xadfb2b69" }, // TAPEOUT_FEE()
    ]);
    out.preflight = {
      project,
      circuitsSoFar: nextId && nextId.length > 2 ? Number(BigInt(nextId)) : "unreadable",
      tapeoutFeeWei: fee && fee.length > 2 ? BigInt(fee).toString() : "unreadable",
    };
  }
  if (ruleId) {
    const [info] = await batchCall([{ to: POPCOUNT8.cpu, data: callData(SEL.circuitInfo, POPCOUNT8.id) }]);
    out.preflight = { ...(out.preflight || {}), popcount8Alive: !!info };
  }

  // dry-run the tapeout call: it must reach the token burn (ERC1155InsufficientBalance)
  if (project) {
    const res = await fetch(process.env.RPC || "https://bsc-rpc.publicnode.com", {
      method: "POST", headers: { "content-type": "application/json" },
      body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "eth_call", params: [{
        from: "0x000000000000000000000000000000000000dEaD", to: project,
        data: out.steps.find((s) => s.step === 2).calldata, value: "0xb5e620f48000",
      }, "latest"] }),
    }).then((r) => r.json());
    const d = res.error?.data || "";
    // 0x03dee4c5 = ERC1155InsufficientBalance(address,uint256,uint256,uint256)
    out.preflight = { ...(out.preflight || {}), calldataReachesTokenBurn: String(d).startsWith("0x03dee4c5"), revert: String(d).slice(0, 10) };
  }

  fs.mkdirSync("out", { recursive: true });
  fs.writeFileSync("out/calldata.json", JSON.stringify(out, null, 2));
  console.log(JSON.stringify(out, (k, v) => (typeof v === "string" && v.length > 120 ? v.slice(0, 60) + `…(${v.length} chars)` : v), 2));
  console.log("\nfull calldata written to out/calldata.json — nothing was sent");
}
